### PR TITLE
Feature: Update packages & run app and pages directories in parallel

### PR DESCRIPTION
**Pull request by jonsherrard**
Addresses some of the concerns in https://github.com/tamagui/tamagui/issues/2589

- Updates to latest Next 14
- Updates to Solito 4
- Updates packages in general

- Runs App Directory Routes AND Pages Directory routes in parallel
- Crucially switches to using app directory as the default

```sh
├── apps
│   ├── next
│       ├── app
│       │   ├── TamaguiProvider.tsx
│       │   ├── layout.tsx
│       │   ├── page.tsx # Root /
│       │   └── user
│       │       └── [id]
│       │           └── page.tsx # /user/nate
│       ├── pages
│       │   ├── _app.tsx
│       │   ├── _document.tsx
│       │   ├── pages-example
│       │   │   └── index.tsx # /pages-example
│       │   └── pages-example-user
│       │       └── [id].tsx # /pages-example-user/nate
│       ├── tsconfig.json
│       ├── types.d.tsA
│       ├── next-env.d.ts
│       ├── package.json
│       └── vercel.json
├── package.json
```

### CODE REVIEW

**Comment by kaumac** [comment]
Hey @jonsherrard thanks for looking into this so quickly!

Everything looks good to me. The only thing I'd note is that it'd be great to have the toast working on all platforms (I understand this might not be directly related to this PR).

On the T4 stack starter they have built a toast that works both on web and on mobile:
https://github.com/timothymiller/t4-app

TBH I'm quite new to Tamagui and Expo so I don't quite understand what the difference is between the two starters

**Comment by jonsherrard** [comment]
@natew I also have an update here that I think would make the starter more approachable.

It probably needs a note on watching and building the `ui` package as well.

https://github.com/jonsherrard/starter-free/pull/1

**Comment by kaumac** [comment]
@jonsherrard another fun one:
I noticed that the starter-free comes with a `turbo.json` file, but it doen't take advantage of turborepo.

For example, instead of:
`"web": "yarn build && cd apps/next && yarn next"`

On my project I do:
`turbo dev --parallel --filter={@web,@ui}`

With this I avoid the "cd'ing"into directories which might be confusing and run next and the tamagui ui scripts in parallel.

Just a suggestion because there's already a turbo.json on the starter

**Comment by natew** [comment]
Huge, thanks for this amazing work. Once I get a chance I'll test this out and get it merged. I know we need to revisit RSC and improve a few things too.

**Comment by jonsherrard** [comment]
Awesome. One thing that will need updating is the Expo side. I tried to give it a go, but Expo is totally broken on my laptop at the minute and I totally ran out of time. I can't even `create-expo-app`.

It should just be a case of fetching the [id] from createParams in new Solito 4 world and passing it to the <UserDetails /> screen.

Also let me know thoughts on https://github.com/jonsherrard/starter-free/pull/1 - if it's useful I can raise another PR

**Pull request merged**
